### ISSUE TITLE
Template command seems broken

### ISSUE THREAD

**Issue by abusch** [edthedev/minion#37]
Just installed minion and running `mn template journal` fails with the following stack (the filename of the template is wrong):

```
Traceback (most recent call last):
  File "/home/abusch/.local/bin/minion", line 568, in <module>
    locals()[method]()
  File "/home/abusch/.local/bin/minion", line 199, in minion_template
    brain.new_note_interactive(**params)
  File "/home/abusch/.config/vim/bundle/minion/brain_of_minion.py", line 1367, in new_note_interactive
    (filename, last_line) = create_new_note(topic, note_template, notes_dir)
  File "/home/abusch/.config/vim/bundle/minion/brain_of_minion.py", line 1390, in create_new_note
    template_content = get_template_content(note_template)
  File "/home/abusch/.config/vim/bundle/minion/brain_of_minion.py", line 1319, in get_template_content
    f = open(template_file, 'r')
IOError: [Errno 2] No such file or directory: "/home/abusch/.config/vim/bundle/minion/templates/['journal']_template.txt"
```

**Comment by edthedev** [comment]
Confirmed in master. Will get a test and a fix added shortly.

**Comment by edthedev** [comment]
Corrected by d1f80d6ad70cfb64. Hotfix version is now 1.9.4, and Master branch is up to date.
If you 'git pull', or update with your favorite Vim plugin manager, you will receive the fix.

Sorry for any inconvenience.

**Comment by edthedev** [comment]
Commenting again, after pushing, so that the commit link (d1f80d6ad70cfb64) links nicely.

**Comment by abusch** [comment]
Well, that was quick :) Thanks!

**Comment by edthedev** [comment]
You're welcome. Thanks for letting me know!
